using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlazorClientDemo.Data.ViewModels
{
    public class DogBreedTypesResponseVM
    {
        public List<string> affenpinscher { get; set; } = new List<string>();
        public List<string> african { get; set; } = new List<string>();
        public List<string> airedale { get; set; } = new List<string>();
        public List<string> akita { get; set; } = new List<string>();
        public List<string> appenzeller { get; set; } = new List<string>();
        public List<string> australian { get; set; } = new List<string>();
        public List<string> basenji { get; set; } = new List<string>();
        public List<string> beagle { get; set; } = new List<string>();
        public List<string> bluetick { get; set; } = new List<string>();
        public List<string> borzoi { get; set; } = new List<string>();
        public List<string> bouvier { get; set; } = new List<string>();
        public List<string> boxer { get; set; } = new List<string>();
        public List<string> brabancon { get; set; } = new List<string>();
        public List<string> briard { get; set; } = new List<string>();
        public List<string> buhund { get; set; } = new List<string>();
        public List<string> bulldog { get; set; } = new List<string>();
        public List<string> bullterrier { get; set; } = new List<string>();
        public List<string> cattledog { get; set; } = new List<string>();
        public List<string> chihuahua { get; set; } = new List<string>();
        public List<string> chow { get; set; } = new List<string>();
        public List<string> clumber { get; set; } = new List<string>();
        public List<string> cockapoo { get; set; } = new List<string>();
        public List<string> collie { get; set; } = new List<string>();
        public List<string> coonhound { get; set; } = new List<string>();
        public List<string> corgi { get; set; } = new List<string>();
        public List<string> cotondetulear { get; set; } = new List<string>();
        public List<string> dachshund { get; set; } = new List<string>();
        public List<string> dalmatian { get; set; } = new List<string>();
        public List<string> dane { get; set; } = new List<string>();
        public List<string> deerhound { get; set; } = new List<string>();
        public List<string> dhole { get; set; } = new List<string>();
        public List<string> dingo { get; set; } = new List<string>();
        public List<string> doberman { get; set; } = new List<string>();
        public List<string> elkhound { get; set; } = new List<string>();
        public List<string> entlebucher { get; set; } = new List<string>();
        public List<string> eskimo { get; set; } = new List<string>();
        public List<string> finnish { get; set; } = new List<string>();
        public List<string> frise { get; set; } = new List<string>();
        public List<string> germanshepherd { get; set; } = new List<string>();
        public List<string> greyhound { get; set; } = new List<string>();
        public List<string> groenendael { get; set; } = new List<string>();
        public List<string> havanese { get; set; } = new List<string>();
        public List<string> hound { get; set; } = new List<string>();
        public List<string> husky { get; set; } = new List<string>();
        public List<string> keeshond { get; set; } = new List<string>();
        public List<string> kelpie { get; set; } = new List<string>();
        public List<string> komondor { get; set; } = new List<string>();
        public List<string> kuvasz { get; set; } = new List<string>();
        public List<string> labradoodle { get; set; } = new List<string>();
        public List<string> labrador { get; set; } = new List<string>();
        public List<string> leonberg { get; set; } = new List<string>();
        public List<string> lhasa { get; set; } = new List<string>();
        public List<string> malamute { get; set; } = new List<string>();
        public List<string> malinois { get; set; } = new List<string>();
        public List<string> maltese { get; set; } = new List<string>();
        public List<string> mastiff { get; set; } = new List<string>();
        public List<string> mexicanhairless { get; set; } = new List<string>();
        public List<string> mix { get; set; } = new List<string>();
        public List<string> mountain { get; set; } = new List<string>();
        public List<string> newfoundland { get; set; } = new List<string>();
        public List<string> otterhound { get; set; } = new List<string>();
        public List<string> ovcharka { get; set; } = new List<string>();
        public List<string> papillon { get; set; } = new List<string>();
        public List<string> pekinese { get; set; } = new List<string>();
        public List<string> pembroke { get; set; } = new List<string>();
        public List<string> pinscher { get; set; } = new List<string>();
        public List<string> pitbull { get; set; } = new List<string>();
        public List<string> pointer { get; set; } = new List<string>();
        public List<string> pomeranian { get; set; } = new List<string>();
        public List<string> poodle { get; set; } = new List<string>();
        public List<string> pug { get; set; } = new List<string>();
        public List<string> puggle { get; set; } = new List<string>();
        public List<string> pyrenees { get; set; } = new List<string>();
        public List<string> redbone { get; set; } = new List<string>();
        public List<string> retriever { get; set; } = new List<string>();
        public List<string> ridgeback { get; set; } = new List<string>();
        public List<string> rottweiler { get; set; } = new List<string>();
        public List<string> saluki { get; set; } = new List<string>();
        public List<string> samoyed { get; set; } = new List<string>();
        public List<string> schipperke { get; set; } = new List<string>();
        public List<string> schnauzer { get; set; } = new List<string>();
        public List<string> setter { get; set; } = new List<string>();
        public List<string> sheepdog { get; set; } = new List<string>();
        public List<string> shiba { get; set; } = new List<string>();
        public List<string> shihtzu { get; set; } = new List<string>();
        public List<string> spaniel { get; set; } = new List<string>();
        public List<string> springer { get; set; } = new List<string>();
        public List<string> stbernard { get; set; } = new List<string>();
        public List<string> terrier { get; set; } = new List<string>();
        public List<string> tervuren { get; set; } = new List<string>();
        public List<string> vizsla { get; set; } = new List<string>();
        public List<string> waterdog { get; set; } = new List<string>();
        public List<string> weimaraner { get; set; } = new List<string>();
        public List<string> whippet { get; set; } = new List<string>();
        public List<string> wolfhound { get; set; } = new List<string>();

    }
}
